/*
 * trungpvpp02786
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package panelFrame;

/**
 *
 * @author catty
 */
public class tutorialPanel extends javax.swing.JPanel {

    /**
     * Creates new form tutorialPanel
     */
    public tutorialPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtIntro = new javax.swing.JTextPane();

        jLabel1.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Hướng dẫn");

        txtIntro.setEditable(false);
        txtIntro.setText("Hướng dẫn sử dụng các chức năng:\n\nQuản lý nhân viên: Có thể xem danh sách, thêm mới bằng cách nhập đầy đủ thông tin. Sửa, xóa thông tin khi cần thiết.\n\n" +
            "Quản lý người học: Tương tự quản lý danh sách học sinh, sinh viên. Có thể lọc theo lớp, khoá học.\n\n" +
            "Quản lý chuyên đề: Thêm mới, sửa cập nhật nội dung chi tiết của từng môn học, chuyên đề. Phân quyền giáo viên phụ trách.\n\n" +
            "Quản lý khóa học: Thiết lập cấu trúc khóa học, thời gian học tập. Phân bổ giáo viên, lớp học.\n\n" +
            "Tổng hợp thống kê: Xem biểu đồ doanh thu theo thời gian, khóa học. Bảng điểm chi tiết các học viên.\n\nQuản lý học viên: Thêm các hoạt động theo dõi tiến độ, điểm số, kết quả học tập của người học.\n\n" +
            "Đăng nhập, đăng xuất hệ thống và phân quyền truy cập cho các thành phần.");
        jScrollPane1.setViewportView(txtIntro);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 263, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextPane txtIntro;
    // End of variables declaration//GEN-END:variables
}
